### ISSUE TITLE
XrmOssXrmHtmlTemplating_1_3_0_target_CRM_8.0_managed.zip

### ISSUE THREAD

**Issue by phuocle** [DigitalFlow/Xrm-Html-Templating#14]
Install failed

![image](https://user-images.githubusercontent.com/479729/76191238-754a6f80-6211-11ea-8316-ab41b1e2a613.png)

**Comment by DigitalFlow** [comment]
Hi @phuocle,

Could you please install [XTL](https://github.com/DigitalFlow/Xrm-Templating-Language) first?
It is a dependency which seems to be missing in the ReadMe, I'll edit it.
I plan to support Email Previews with combined XTL Template expressions (integration already works), so the other solution is needed.

Kind Regards,
Florian
