### ISSUE TITLE
Missing table in rendered email

### ISSUE THREAD

**Issue by andreaPorini** [DigitalFlow/Xrm-Html-Templating#15]
Hi @DigitalFlow ,

I have an issue rendering a table in an Email record using an HTML Template.

This is the function for the table:
`${{RecordTable ( Fetch ( "<fetch top='5' no-lock='true'><entity name='lfr_transaction'><attribute name='lfr_totalamount'/><attribute name='lfr_storeid'/><attribute name='lfr_date'/><filter type='and'><condition attribute='lfr_cardid' operator='eq' value='{1}'/></filter></entity></fetch>", Array(Value("regardingobjectid") )), "lfr_transaction", ["lfr_totalamount","lfr_storeid","lfr_date"], {addRecordUrl: true} ) }}`

The fetch is returing 5 values (tested) and I've also tested the function inside the Templating Language solution, the table is being rendered (there are many <br> tags before the table but i don't think this is the issue).

I'm in an Online enviroment, latest release using the UCI. I've also installed the latest release of your solutions (Templating Language and HTML Templating).

Do you have any suggestion about this issue?

Best regards,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

Could you please post the raw html text which gets set in your email description and the debugger output inside the Template Language editor? That would help me understanding what is happening at your side.

My first thought would be: As it is working inside the editor but not in your organization, the plugin step might be missing the organizationUrl inside its config. Did you by any chance import the template step via a solution to your organization? In that case you would have to save the step again in your target solution to revive the configuration.

You can just press on save and try again. If it is still not working, please leave out the "{addRecordUrl: true}" and check if it works.

Kind Regards,
Florian

**Comment by andreaPorini** [comment]
Thank you Florian,

I always forget about the organizationUrl configuration! Opening and saving again all the steps solved my problem!

Is there a way, maybe in the solution config page, to set the organizationUrl for all the steps? It would definitely be simplier to view if the configuration is missing.
Only because I always forget about this setting 😄 

Thank you for the quick response!

Best regards,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

I'm glad that you got it working 👍 
I'll think of a way to set missing secure configs in bulk, good idea.

Kind Regards,
Florian
