### ISSUE TITLE
Plugin error on Email creation without template

### ISSUE THREAD

**Issue by andreaPorini** [DigitalFlow/Xrm-Html-Templating#3]
Hi Florian,

thank you for your work, like the Xrm Templating Language, also this tool is amazing.

I found an issue on one of your default plugins registered within the solution: Xrm.Oss.XTL.Templating.XTLProcessor: Create of email (Apply XTL placeholders).

If i create an email without the template lookup valorized i get this error:

> Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Unexpected exception from plug-in (Execute): Xrm.Oss.XTL.Templating.XTLProcessor: System.ArgumentNullException: Value cannot be null.
> Parameter name: inputDetail: 
> OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
>   ActivityId>bcb931bb-5830-4ff4-a9bf-cecd7d9d7dc8</ActivityId>
>   ErrorCode>-2147220956</ErrorCode>
>   ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
>   Message>Unexpected exception from plug-in (Execute): Xrm.Oss.XTL.Templating.XTLProcessor: System.ArgumentNullException: Value cannot be null.
> Parameter name: input</Message>
>   Timestamp>2018-11-30T14:31:40.4130753Z</Timestamp>
>   ExceptionRetriable>false</ExceptionRetriable>
>   ExceptionSource i:nil="true" />
>   InnerFault i:nil="true" />
>   OriginalException i:nil="true" />
>   TraceText>
> 
> [Xrm.Oss.XTL.Templating: Xrm.Oss.XTL.Templating.XTLProcessor]
> [fb642c1d-a9da-e811-80ee-0050568e4745: Xrm.Oss.XTL.Templating.XTLProcessor: Create of email (Apply XTL placeholders)]
> 
> Initiating interpreter
> Processing handler IsEqual
> Processing handler Value
> Successfully processed handler Value
> Successfully processed handler IsEqual
> 
> 
> </TraceText>
> </OrganizationServiceFault>

I solved the issue adding another condition for the plugin execution criteria:

> And(IsEqual ( Value ( "directioncode" ), true ), Not(IsNull(Value("oss_htmltemplate"))))

I hope this is helpful for you.

Keep up the good work!

Best regards,
Andrea

**Comment by DigitalFlow** [comment]
Hi Andrea,

thanks for getting in touch, I'm glad that you like this project.

I'll take a look at this issue, I think it might be related to an XTL issue which i lately filed.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

I fixed this bug directly in XTL, installing XTL in version >= 3.2.2 fixes this issue.
Thanks for reporting it.

Kind Regards,
Florian
