### ISSUE TITLE
Adding value to the template from a Workflow/Action

### ISSUE THREAD

**Issue by andreaPorini** [DigitalFlow/Xrm-Html-Templating#5]
Hi Florian,

as usual, thank you for your work on this tool, awesome.

I'd like to suggest a feature that could be very useful for templating, for example, an Email.

I've been requested to send a reminder for a record of Appointment entity and I've created an HTML Template, but, as you might know, by standard I cannot insert into the Regarding field the lookup to the appointment record; the problem is that I'd like to insert into the template the start time and the location of the appointment which has to be reminded of and I cannot use the standard tags, like {Start Time(Appointment)}, that i can obtain from my action.

Do you have some guess of how to do it? Maybe there is already a way to solve my problem and I missed it!

Best regards,
Andrea

**Comment by DigitalFlow** [comment]
Hi Andrea,

thanks for getting in touch.
You can do this without any issues, the templating is not bound to the regarding object.

The easiest way would be to customize your E-Mail entity with a new Lookup which points to appointments and to fill it inside your workflow.
Then inside the template, just use ${{Value("yourAppointmentLookup.starttime")}}.

Let me know if this solves your problem.

Kind Regards,
Florian

**Comment by andreaPorini** [comment]
Yeah I thought about that too but this is bound to the presence of the relation Email-Appointment; I'd like to add the information without creating the relationship also because if I have to obtain another information from another Entity I'd be obliged to add another relation.

If there isn't another way I'll follow your advice.

Thank you,
Andrea

**Comment by andreaPorini** [comment]
Hi @DigitalFlow,

in the end I went with your first advice, We want to make our template the most user-friendly possibile so the easiest way to make a non-tecnichal user understand what the template is doing is adding a new relationship.

Thank you for your time!

I saw some problems with the copy-paste functionality in the HTML templating tool, sometimes if I paste  the ${{Value("")}} keyword the templating language is not catching it; i don't know if this is a problem of the Unlayer Editor tool or of the Templating Language. I solved this writing by hand all the keywords of the templating tool so it's not an important problem but I'd like to let you know.

As always, thank you.

Best regards,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

yes, pasting into the unlayer editor causes issues sometimes, as pasting directly from another webpage often includes html <p> or <span> tags, which breaks the XTL expressions.
I often paste into Notepad first before pasting into the unlayer editor.

But the best workaround is possibly to paste the XTL templates into unlayer HTML components, because there no special actions happen upon pasting expressions.
So whenever possible, I'd suggest to do it like that.
Writing by hand solves it as well, that's correct.

You're very welcome, I'm happy that you enjoy this tool.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Short follow up @andreaPorini:
As it turns out, your browser is already capable of pasting copied text withour formatting into the templates.
Instead of using Ctrl + V, you can either use Ctrl + Shift + V or right click where you want to paste and click on "Paste unformatted".
